version: "2"

linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - funcorder
    - gocyclo
    - godot
    - godox
    - gosec
    - ineffassign
    - intrange
    - loggercheck
    - mnd
    - nilerr
    - nilnil
    - reassign
    - testifylint
    - unconvert
    - unparam
    - varnamelen
    - wastedassign

run:
  concurrency: 4
  timeout: 5m
  tests: false
